# Minimal self-contained CRDs useful for operator exercises and demos.
# These CRDs are examples (group "ops.kubeskills.io") and safe to apply to any cluster.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.ops.kubeskills.io
spec:
  group: ops.kubeskills.io
  names:
    kind: App
    plural: apps
    singular: app
    shortNames: ["kfsapp"]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["image"]
              properties:
                image:
                  type: string
                  pattern: "^[\w./:-]+$"
                replicas:
                  type: integer
                  minimum: 0
                env:
                  type: array
                  items:
                    type: object
                    required: ["name","value"]
                    properties:
                      name: { type: string }
                      value: { type: string }
            status:
              type: object
              properties:
                readyReplicas: { type: integer }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.ops.kubeskills.io
spec:
  group: ops.kubeskills.io
  names:
    kind: Policy
    plural: policies
    singular: policy
    shortNames: ["kfspol"]
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  enum: ["deny-egress","image-allowlist","pss-restricted"]
                params:
                  type: object
                  additionalProperties: true
