# loki-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.x.x"
    helm:
      releaseName: loki
      valueFiles:
      - $values/infrastructure/monitoring/loki/values.yaml
  - repoURL: https://github.com/your-username/your-repo.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true